# This is used for building the app and running integration tests
# You can also run it locally:
#
# docker-compose up --build --abort-on-container-exit --force-recreate
version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ./target:/app/target
      - $HOME/.m2/:/root/.m2/:rw
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dundie
      - SPRING_DATA_REDIS_HOST=redis
    command: mvn install -s ./settings.xml

  postgres:
    image: postgres:13.10-alpine
    environment:
      - POSTGRES_DB=dundie
      - POSTGRES_USER=dundie
      - POSTGRES_PASSWORD=dundie

  redis:
    image: redis:6.2.6-alpine
