springdoc:
  api-docs:
    path: /openapi
server:
  port: 3000
  error:
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dundie
    username: dundie
    password: dundie
  jpa:
    show-sql: false # change to true for debugging
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    database: postgresql
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/static/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  data:
    redis:
      host: localhost
      port: 6379

redis:
  ttl:
    dundie-awards: 1h
    employees: 2h

message-broker:
  delay-milliseconds: 500

data-loader:
  enabled: false

--- ########################################################################
spring.config.activate.on-profile: integration-test

message-broker:
  delay-milliseconds: 50

data-loader:
  enabled: false
--- ########################################################################
spring.config.activate.on-profile: local

data-loader:
  enabled: true

message-broker:
  delay-milliseconds: 8000

--- ########################################################################
spring.config.activate.on-profile: staging

--- ########################################################################
spring.config.activate.on-profile: prod
